[{
	"name": "bkz_apricity"
}, {
	"name": "bkz_blackrockshooter_vzp"
}, {
	"name": "bkz_bonus_z1"
}, {
	"name": "bkz_cauz_final"
}, {
	"name": "bkz_caves_go"
}, {
	"name": "bkz_cg_coldbhop"
}, {
	"name": "bkz_goldbhop_csgo"
}, {
	"name": "bkz_goldbhop_v2go"
}, {
	"name": "bkz_hellokitty_v2"
}, {
	"name": "bkz_impulse"
}, {
	"name": "bkz_levite_ng"
}, {
	"name": "bkz_measure"
}, {
	"name": "bkz_measure2_b03"
}, {
	"name": "bkz_nocturns_blue"
}, {
	"name": "bkz_sahara_v2"
}, {
	"name": "bkz_synergy_ez"
}, {
	"name": "bkz_synergy_x"
}, {
	"name": "bkz_underground_crypt_v3"
}, {
	"name": "bkz_uninspired_trash"
}, {
	"name": "kz_2seasons_spring_fix"
}, {
	"name": "kz_2seasons_winter_fix"
}, {
	"name": "kz_21loop_final_fix"
}, {
	"name": "kz_7in1_go"
}, {
	"name": "kz_adrenaline"
}, {
	"name": "kz_adventure"
}, {
	"name": "kz_adv_cursedjourney"
}, {
	"name": "kz_after_agitation_easy_fix"
}, {
	"name": "kz_agility_v2_fix"
}, {
	"name": "kz_ahful"
}, {
	"name": "kz_akrh_warehouse"
}, {
	"name": "kz_alouette"
}, {
	"name": "kz_ancient_v3"
}, {
	"name": "kz_asphyxiate"
}, {
	"name": "kz_asteroid_field_go"
}, {
	"name": "kz_aztec"
}, {
	"name": "kz_basics_b02"
}, {
	"name": "kz_beginnerblock_go"
}, {
	"name": "kz_betterdunjun"
}, {
	"name": "kz_basicnoon"
}, {
	"name": "kz_bhop_essence"
}, {
	"name": "kz_bhop_forchi"
}, {
	"name": "kz_bhop_lj"
}, {
	"name": "kz_bhop_mosaic_od"
}, {
	"name": "kz_bhop_northface"
}, {
	"name": "kz_bhop_watertemple"
}, {
	"name": "kz_bionic"
}, {
	"name": "kz_blindcity_easy_fix"
}, {
	"name": "kz_blindcity_hard_final"
}, {
	"name": "kz_brickblock_v2"
}, {
	"name": "kz_brightblock"
}, {
	"name": "kz_buildings_final"
}, {
	"name": "kz_cakewalk"
}, {
	"name": "kz_canyon"
}, {
	"name": "kz_cargo"
}, {
	"name": "kz_cascade_v3"
}, {
	"name": "kz_cataclysm"
}, {
	"name": "kz_catalyst"
}, {
	"name": "kz_catharsis_global"
}, {
	"name": "kz_caulis_v2"
}, {
	"name": "kz_caverns_deep_go"
}, {
	"name": "kz_cellblock_go2"
}, {
	"name": "kz_cg_brick_rmk"
}, {
	"name": "kz_cg_lighthops_go"
}, {
	"name": "kz_chessblock"
}, {
	"name": "kz_chinablock"
}, {
	"name": "kz_christmas_fix"
}, {
	"name": "kz_cliffhanger_go_global"
}, {
	"name": "kz_colorcode"
}, {
	"name": "kz_colors_v2"
}, {
	"name": "kz_combohop_c02"
}, {
	"name": "kz_communityjump3"
}, {
	"name": "kz_complex"
}, {
	"name": "kz_comp_global"
}, {
	"name": "kz_concretejungle"
}, {
	"name": "kz_conrun_mq"
}, {
	"name": "kz_conrun_scrub"
}, {
	"name": "kz_construction"
}, {
	"name": "kz_cratespeed"
}, {
	"name": "kz_crate_delight_go"
}, {
	"name": "kz_crypt_final"
}, {
	"name": "kz_crysis"
}, {
	"name": "kz_cyb_adrenaline"
}, {
	"name": "kz_dam"
}, {
	"name": "kz_de_bhop"
}, {
	"name": "kz_default"
}, {
	"name": "kz_depot"
}, {
	"name": "kz_dimensions_v1"
}, {
	"name": "kz_district_d01"
}, {
	"name": "kz_dontstop"
}, {
	"name": "kz_doubletake"
}, {
	"name": "kz_doveen"
}, {
	"name": "kz_drops_od"
}, {
	"name": "kz_dryness"
}, {
	"name": "kz_duality"
}, {
	"name": "kz_dungeon"
}, {
	"name": "kz_dvn_cube_fixed"
}, {
	"name": "kz_dvn_dull"
}, {
	"name": "kz_dvn_redcarpet"
}, {
	"name": "kz_dzy_beyond"
}, {
	"name": "kz_dzy_reach"
}, {
	"name": "kz_ea_beneath_go"
}, {
	"name": "kz_emblem"
}, {
	"name": "kz_emblem_bonus"
}, {
	"name": "kz_ephemeral"
}, {
	"name": "kz_epusbridge"
}, {
	"name": "kz_erinome"
}, {
	"name": "kz_excape"
}, {
	"name": "kz_excavate"
}, {
	"name": "kz_exoteric"
}, {
	"name": "kz_experiment"
}, {
	"name": "kz_exps_cursedjourney"
}, {
	"name": "kz_ext_bblocks"
}, {
	"name": "kz_fabrik"
}, {
	"name": "kz_failed_fastrun_rt"
}, {
	"name": "kz_farm"
}, {
	"name": "kz_fastcombomap"
}, {
	"name": "kz_fatigue_v2"
}, {
	"name": "kz_fikablock"
}, {
	"name": "kz_final_ascension"
}, {
	"name": "kz_floatingislands"
}, {
	"name": "kz_forestrace_go"
}, {
	"name": "kz_frozen_go"
}, {
	"name": "kz_futureblock"
}, {
	"name": "kz_galaxy_go2"
}, {
	"name": "kz_genesis_go2"
}, {
	"name": "kz_gfy_blueberry"
}, {
	"name": "kz_gfy_c0mb0king"
}, {
	"name": "kz_gfy_devcastle"
}, {
	"name": "kz_gfy_final"
}, {
	"name": "kz_gfy_fortroca_finallll"
}, {
	"name": "kz_gfy_limit"
}, {
	"name": "kz_gfy_tech"
}, {
	"name": "kz_giantbean"
}, {
	"name": "kz_gigablock_go"
}, {
	"name": "kz_gitgud_final"
}, {
	"name": "kz_glassesospa_v1"
}, {
	"name": "kz_goldenroad"
}, {
	"name": "kz_gonbe"
}, {
	"name": "kz_grass_hard"
}, {
	"name": "kz_green"
}, {
	"name": "kz_gurk"
}, {
	"name": "kz_gy_agitation"
}, {
	"name": "kz_haki_v2"
}, {
	"name": "kz_heatvents_mq"
}, {
	"name": "kz_hellinashop"
}, {
	"name": "kz_highland"
}, {
	"name": "kz_high_tech"
}, {
	"name": "kz_hillside"
}, {
	"name": "kz_illusion"
}, {
	"name": "kz_iluvprok_global"
}, {
	"name": "kz_insomnia_fix"
}, {
	"name": "kz_inspired"
}, {
	"name": "kz_internatus"
}, {
	"name": "kz_island"
}, {
	"name": "kz_j2s_tetris_go"
}, {
	"name": "kz_j2s_cupblock_go_fix2"
}, {
	"name": "kz_j2s_westbl0ck"
}, {
	"name": "kz_janpu_final_fix"
}, {
	"name": "kz_jumpspace_easy"
}, {
	"name": "kz_jump_n_run"
}, {
	"name": "kz_kingsbay_v2"
}, {
	"name": "kz_kzinga_fixed"
}, {
	"name": "kz_kzse_aztectemple"
}, {
	"name": "kz_lavablock_global"
}, {
	"name": "kz_lego"
}, {
	"name": "kz_lego_two_redux_v3"
}, {
	"name": "kz_levels"
}, {
	"name": "kz_littlerock_v2"
}, {
	"name": "kz_mac"
}, {
	"name": "kz_magus"
}, {
	"name": "kz_marblewalls_fixed"
}, {
	"name": "kz_metalrun_global"
}, {
	"name": "kz_mike_v4"
}, {
	"name": "kz_minimountain_fix"
}, {
	"name": "kz_morebricks_msq"
}, {
	"name": "kz_motivated"
}, {
	"name": "kz_msp_comatose"
}, {
	"name": "kz_natureblock_go"
}, {
	"name": "kz_nature_csgo"
}, {
	"name": "kz_neon_portal"
}, {
	"name": "kz_nightfall_fixed"
}, {
	"name": "kz_nightmare_v2"
}, {
	"name": "kz_nuckfoobs_n01"
}, {
	"name": "kz_nyc_v1"
}, {
	"name": "kz_oasis"
}, {
	"name": "kz_obsidian"
}, {
	"name": "kz_ominous2"
}, {
	"name": "kz_orbolution_v2"
}, {
	"name": "kz_pantheism_p02"
}, {
	"name": "kz_paradise"
}, {
	"name": "kz_peak_global"
}, {
	"name": "kz_phamous"
}, {
	"name": "kz_pharaoh_csgo"
}, {
	"name": "kz_phaztec"
}, {
	"name": "kz_pianoclimb_go"
}, {
	"name": "kz_pollution"
}, {
	"name": "kz_portal_1"
}, {
	"name": "kz_prismus"
}, {
	"name": "kz_project"
}, {
	"name": "kz_psytime_go"
}, {
	"name": "kz_quadrablock"
}, {
	"name": "kz_quadrant"
}, {
	"name": "kz_quick7_v2"
}, {
	"name": "kz_quickshot"
}, {
	"name": "kz_quixotic"
}, {
	"name": "kz_railings"
}, {
	"name": "kz_rainrun_kn_f"
}, {
	"name": "kz_reach"
}, {
	"name": "kz_redemption_csgo"
}, {
	"name": "kz_redline"
}, {
	"name": "kz_remedy_v2"
}, {
	"name": "kz_retribution_v2_final"
}, {
	"name": "kz_return"
}, {
	"name": "kz_rise"
}, {
	"name": "kz_rockclimb"
}, {
	"name": "kz_rockjungle_v2"
}, {
	"name": "kz_rocks_global"
}, {
	"name": "kz_sanctuary"
}, {
	"name": "kz_sandstone_mq"
}, {
	"name": "kz_sandyhill_hoc"
}, {
	"name": "kz_sendhelp_final"
}, {
	"name": "kz_serenity"
}, {
	"name": "kz_shark"
}, {
	"name": "kz_signs_v2"
}, {
	"name": "kz_simplicity_v2"
}, {
	"name": "kz_skyhotel"
}, {
	"name": "kz_skytower_final"
}, {
	"name": "kz_snowman_v2"
}, {
	"name": "kz_snowtrain_v2"
}, {
	"name": "kz_solidarity_v2"
}, {
	"name": "kz_spacus"
}, {
	"name": "kz_spiritblockv2"
}, {
	"name": "kz_streetblock_go"
}, {
	"name": "kz_strun_mq"
}, {
	"name": "kz_stuff_final"
}, {
	"name": "kz_sukblock_v2_fixed"
}, {
	"name": "kz_summercliff2_go"
}, {
	"name": "kz_sunset_od"
}, {
	"name": "kz_symbiosis_final"
}, {
	"name": "kz_synthesis_v2"
}, {
	"name": "kz_sz_halicarnassus"
}, {
	"name": "kz_talltreeforest_v3"
}, {
	"name": "kz_teh"
}, {
	"name": "kz_terablock"
}, {
	"name": "kz_toonadventure_go"
}, {
	"name": "kz_toonrun_final"
}, {
	"name": "kz_toughluck_v2"
}, {
	"name": "kz_tour_de_nuke_global"
}, {
	"name": "kz_tradeblock_go"
}, {
	"name": "kz_trashsurf"
}, {
	"name": "kz_tron_global"
}, {
	"name": "kz_tryit_v2"
}, {
	"name": "kz_unity_u01"
}, {
	"name": "kz_vci_apprentice"
}, {
	"name": "kz_verv3_gg"
}, {
	"name": "kz_village_lp"
}, {
	"name": "kz_violet_fix"
}, {
	"name": "kz_void"
}, {
	"name": "kz_walpurgisnacht"
}, {
	"name": "kz_warehouse"
}, {
	"name": "kz_whatever_v2"
}, {
	"name": "kz_woodstock_v2"
}, {
	"name": "kz_woodstonegrass_final"
}, {
	"name": "kz_woodworld"
}, {
	"name": "kz_xand"
}, {
	"name": "kz_xtremeblock_v2"
}, {
	"name": "kz_za_tileblock"
}, {
	"name": "kz_zeta_z3"
}, {
	"name": "kz_ziggurath_final"
}, {
	"name": "kz_zhop_freestyle"
}, {
	"name": "kz_zhop_function3"
}, {
	"name": "kz_zhop_son_fix"
}, {
	"name": "kz_zxp_final4"
}, {
	"name": "kz_zxp_undia"
}, {
	"name": "kzpro_concrete_c02"
}, {
	"name": "kzpro_gull_pidr_reborn"
}, {
	"name": "kzpro_module_v2"
}, {
	"name": "bkz_dreamland_global"
}, {
	"name": "bkz_fox_shrine_japan_go2"
}, {
	"name": "bkz_karo4_global"
}, {
	"name": "bkz_lucid_global"
}, {
	"name": "bkz_minecraft2_global"
}, {
	"name": "bkz_minecraft3_global"
}, {
	"name": "bkz_nephilim"
}, {
	"name": "bkz_powerblock_rc1"
}, {
	"name": "bkz_secret_valley_global_fix"
}, {
	"name": "bkz_skycastle_go_b2"
}, {
	"name": "bkz_supermario_go"
}, {
	"name": "bkz_umbrella_global"
}]
